import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {build} from 'esbuild';
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create table contents(id uuid primary key);create table users(id uuid primary key,display_name text);grant select on contents,users to service_role;`);
await db.exec(await readFile('../supabase/changes/discovery_social_v1.sql','utf8'));
const u='11111111-1111-4111-8111-111111111111',v='22222222-2222-4222-8222-222222222222',p='33333333-3333-4333-8333-333333333333',q='44444444-4444-4444-8444-444444444444';
await db.query('insert into users values($1,$2),($3,$4)',[u,'Alice',v,'Bob']);await db.query('insert into contents values($1),($2)',[p,q]);
const write=async(user,post,text,key,parent=null)=>(await db.query('select discovery_comment_write_v1($1,$2,$3,$4,$5) as id',[user,post,text,key,parent])).rows[0].id;
const id=await write(u,p,'<script>test</script>',u);
assert.equal(await write(u,p,'duplicate retry',u),id,'Retry is idempotent');
await assert.rejects(write(u,p,'too fast',v),/comment_rate_limit/);
await assert.rejects(write(v,q,'wrong parent',q,id),/invalid_parent/);
const reply=await write(v,p,'reply',v,id);
const page=(await db.query('select discovery_comments_page_v1($1,$2) as data',[u,p])).rows[0].data;
assert.equal(page.length,2);assert.equal(page.find(c=>c.id===id).mine,true);assert.equal(page.find(c=>c.id===reply).mine,false);assert.equal(page.find(c=>c.id===reply).parent.body,'<script>test</script>');assert.equal('user_id' in page[0],false);
await db.exec('set role anon');await assert.rejects(db.query('select * from discovery_comments'),/permission denied/);await assert.rejects(db.query('select discovery_social_stats_v1($1,$2)',[u,[p]]),/permission denied/);await db.exec('reset role');
await db.exec('set role authenticated');await assert.rejects(db.query('select * from discovery_likes'),/permission denied/);await db.exec('reset role');
await db.exec('set role service_role');await db.query('insert into discovery_likes(content_id,user_id) values($1,$2) on conflict do nothing',[p,u]);await db.query('insert into discovery_likes(content_id,user_id) values($1,$2) on conflict do nothing',[p,u]);
assert.equal((await db.query('select discovery_social_stats_v1($1,$2) as data',[u,[p]])).rows[0].data[0].likes,1);
await db.exec('reset role');await db.close();
const code=await build({entryPoints:['../supabase/functions/_shared/social.ts'],bundle:true,write:false,format:'esm',platform:'node'});const {socialRoute}=await import('data:text/javascript;base64,'+Buffer.from(code.outputFiles[0].text).toString('base64'));
let calls=[];const rest=async(path,init)=>{calls.push({path,init});if(path.startsWith('contents?'))return [{id:p}];return [];};const rpc=async(name,args)=>{calls.push({name,args});return [{liked:true,likes:1,comments:0}];};
const run=(path,method,body)=>socialRoute(new Request('https://example.test'+path,{method,body:JSON.stringify(body)}),new URL('https://example.test'+path),path,u,rest,rpc);
assert.equal((await run('/like','POST',{content_id:p,liked:true,user_id:v})).status,200);assert.equal(JSON.parse(calls.find(c=>c.init?.method==='POST').init.body).user_id,u);
calls=[];assert.equal((await run('/comments','DELETE',{content_id:p,comment_id:v,user_id:v})).status,404);assert(calls.some(c=>c.path.includes('user_id=eq.'+u)));
assert.equal((await run('/comments','POST',{content_id:p,text:' ',request_id:u})).status,400);
console.log('Social SQL permissions, rate limit, idempotency, parent scope, private identity and owner-only delete passed');
