create table if not exists public.growth_campaigns (
  id uuid primary key default gen_random_uuid(),
  owner_telegram_user_id bigint not null,
  message text not null,
  status text not null default 'created' check (status in ('created','sending','completed','partial','failed')),
  recipient_count integer not null default 0,
  sent_count integer not null default 0,
  failed_count integer not null default 0,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.growth_campaign_deliveries (
  id bigint generated by default as identity primary key,
  campaign_id uuid not null references public.growth_campaigns(id) on delete cascade,
  telegram_user_id bigint not null,
  chat_id bigint not null,
  status text not null check (status in ('sent','failed')),
  error text,
  created_at timestamptz not null default now(),
  unique(campaign_id, telegram_user_id)
);

create index if not exists growth_campaigns_created_idx
  on public.growth_campaigns(created_at desc);

create index if not exists growth_campaign_deliveries_campaign_idx
  on public.growth_campaign_deliveries(campaign_id, status);

alter table public.growth_campaigns enable row level security;
alter table public.growth_campaign_deliveries enable row level security;

revoke all on public.growth_campaigns from anon, authenticated;
revoke all on public.growth_campaign_deliveries from anon, authenticated;

grant all on public.growth_campaigns to service_role;
grant all on public.growth_campaign_deliveries to service_role;
grant usage, select on all sequences in schema public to service_role;
