create table if not exists public.growth_links (
  id uuid primary key default gen_random_uuid(),
  token text not null unique,
  owner_telegram_user_id bigint not null,
  kind text not null check (kind in ('invite','post')),
  target_id text,
  source text not null default 'miniapp',
  metadata jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists growth_links_active_invite_owner_idx
  on public.growth_links(owner_telegram_user_id)
  where kind = 'invite' and is_active;

create unique index if not exists growth_links_active_post_owner_target_idx
  on public.growth_links(owner_telegram_user_id, target_id)
  where kind = 'post' and is_active;

create index if not exists growth_links_token_kind_idx
  on public.growth_links(token, kind);

create table if not exists public.growth_events (
  id bigint generated by default as identity primary key,
  token text references public.growth_links(token) on delete cascade,
  event_type text not null check (event_type in ('share','miniapp_open')),
  actor_telegram_user_id bigint,
  session_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists growth_events_token_type_created_idx
  on public.growth_events(token, event_type, created_at desc);

create index if not exists growth_events_actor_created_idx
  on public.growth_events(actor_telegram_user_id, created_at desc);

create table if not exists public.bot_marketing_preferences (
  telegram_user_id bigint primary key,
  chat_id bigint not null,
  opted_in boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.growth_links enable row level security;
alter table public.growth_events enable row level security;
alter table public.bot_marketing_preferences enable row level security;

revoke all on public.growth_links from anon, authenticated;
revoke all on public.growth_events from anon, authenticated;
revoke all on public.bot_marketing_preferences from anon, authenticated;

grant all on public.growth_links to service_role;
grant all on public.growth_events to service_role;
grant all on public.bot_marketing_preferences to service_role;
grant usage, select on all sequences in schema public to service_role;
