name: Build React Frontend

on:
  workflow_dispatch:
  push:
    paths:
      - "frontend-react/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: frontend-react
        run: npm install

      - name: Build React
        working-directory: frontend-react
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: telegram-discovery-react-dist
          path: frontend-react/dist
